### ISSUE TITLE
Transaction never mined

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [PegaSysEng/eeajs#19]
Transaction never mined...
I am going through this tutorial line by line http://docs.pantheon.pegasys.tech/en/stable/Privacy/Privacy-Quickstart/
containers are started: 
```
       Name                      Command               State                              Ports
--------------------------------------------------------------------------------------------------------------------------
privacy_bootnode_1    /opt/pantheon/bootnode_sta ...   Up      30303/tcp, 8545/tcp, 8546/tcp
privacy_explorer_1    nginx -g daemon off;             Up      0.0.0.0:32769->80/tcp
privacy_minernode_1   /opt/pantheon/node_start.s ...   Up      30303/tcp, 8545/tcp, 8546/tcp
privacy_node1_1       /opt/pantheon/node_start.s ...   Up      30303/tcp, 0.0.0.0:20000->8545/tcp, 0.0.0.0:20001->8546/tcp
privacy_node2_1       /opt/pantheon/node_start.s ...   Up      30303/tcp, 0.0.0.0:20002->8545/tcp, 0.0.0.0:20003->8546/tcp
privacy_node3_1       /opt/pantheon/node_start.s ...   Up      30303/tcp, 0.0.0.0:20004->8545/tcp, 0.0.0.0:20005->8546/tcp
privacy_orion1_1      /orion/bin/orion data/data ...   Up
privacy_orion2_1      /orion/bin/orion data/data ...   Up
privacy_orion3_1      /orion/bin/orion data/data ...   Up
privacy_rpcnode_1     /opt/pantheon/node_start.s ...   Up      30303/tcp, 8545/tcp, 8546/tcp
****************************************************************
JSON-RPC HTTP service endpoint      : http://localhost:32769/jsonrpc   *
JSON-RPC WebSocket service endpoint : ws://localhost:32769/jsonws   *
Web block explorer address          : http://localhost:32769   *
****************************************************************
```

but transaction never gets mined:
```
node example/eventEmitter.js
Transaction Hash  0x5196ea84bf88308acaea282f2e68f894731e75ca9e4ee0a8cb7f4f8531a03373
Waiting for transaction to be mined ...
Error: Waiting for tx to be mined
    at operation.then.result (/Users/info/_sites/eeajs/src/index.js:46:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NicolasMassart** [comment]
Hi @Vasiliy-Bondarenko 
Could you provide infos on quickstart and eejs versions for us to look at your issue ?
I would need the output of the following commands:
`docker image ls | grep quickstart/`
I would also need the result of the `git show` command on both pantheon-quickstart and eeajs directories where you cloned these projects.
Thanks.

**Comment by MadelineMurray** [comment]
There was an issue in the 1.1.0 version of the quickstart which has been fixed.  At this line: 
http://docs.pantheon.pegasys.tech/en/stable/Privacy/Privacy-Quickstart/#clone-pantheon-quickstart-source-code

Using 1.1.1 instead of 1.1.0 should fix it: 
git clone --branch 1.1.1 https://github.com/PegaSysEng/pantheon-quickstart.git
